### PR TITLE
Enables compatibility with Xcode Version 6.4 (6E35b)

### PR DESCRIPTION
**Pull request by skaramicke**
Relates to #264 amongst others

### CODE REVIEW

**Comment by jurre** [comment]
This is a duplicate of #308

**Comment by skaramicke** [comment]
Yes, yes it is. I don't know why I didn't find #308 when searching! :/ Sorry.

**Comment by jurre** [comment]
No worries, I'll try to merge and release it asap

**Comment by pronebird** [comment]
Thanks for release. Works like a charm.

**Pull request closed without merging**
