### PR TITLE
A one line change to solve a lot of problems installing plugins with nibs!

### PR DESCRIPTION
**Pull request by johnno1962**
Hi, any chance you could you could merge this harmless one line change that solves the problems people have been having using Alcatraz:

https://github.com/supermarin/Alcatraz/issues/196
https://github.com/supermarin/Alcatraz/issues/202
https://github.com/johnno1962/GitDiff/issues/31

This problem has been knocking about for a year now!!

Cheers

### CODE REVIEW

**Comment by johnno1962** [comment]
Don’t know whats up with you CI but I can’t believe it was this change!

**Comment by jurre** [comment]
No, CI has been broken for a while, I was actually planning on just ripping out the failing tests for now as they're clearly not adding any value at this point.

Thanks for the PR!

**Comment by jurre** [comment]
So we remove the existing build first and then re-fetch?

**Comment by johnno1962** [comment]
Thats about the size of it. I’ve tested and this really does resolve the problem. I can’t think of any new ones it would create.

**Comment by jurre** [comment]
I could kind of imagine the fetch failing and this uninstalling your plugin completely?

**Comment by johnno1962** [comment]
not if you delete only the build driectory in Alcatraz's local git clone cache

**Comment by jurre** [comment]
:+1: makes sense, thanks! @supermarin :ship: ?

**Comment by supermarin** [comment]
Hey thanks @jurre and @johnno1962 !

I'm all in for merging it - but I believe it shouldn't live in `ATZGit`.
IMO it should live in plugin installer, and do it before git invocation.

How does that sound?

**Comment by johnno1962** [comment]
Fine by me. Thanks for picking this up! There are a few users who are going to thank you for it.

**Comment by orta** [comment]
this should be closed as #237 fixed it

**Pull request closed without merging**
