### PR TITLE
Set CFBundleShortVersionString before distributing the plugin

### PR DESCRIPTION
**Pull request by guillaume-algis**
This automatically sets `CFBundleShortVersionString` in Alcatraz's Info.plist to the right version number as part of the `build` Makefile target.

### CODE REVIEW

**Comment by guillaume-algis** [comment]
Rebased this PR on top of master. Could you take a look? Thanks!

**Comment by jurre** [comment]
LGTM, @supermarin @kattrali?

**Comment by kattrali** [comment]
LGTM!

**Comment by supermarin** [comment]
LGTM, just misses some context in the PR description  (why do we need it)?

**Comment by guillaume-algis** [comment]
Hmmm, don't really remember my intention when submitting the PR, but I think it stems from the fact that I couldn't figure out easily which version of Alcatraz was installed on my machine.

**Comment by supermarin** [comment]
Gotcha; in that case, here's what I'd suggest:

1. remove ATZVersion.h
2. update install scripts to use `PlistBuddy` instead of `sed`
3. update Alcatraz code to read from plist instead of `ATZVersion`.

Not sure if that sounds reasonable, let me know if you need any pointers :)

**Comment by guillaume-algis** [comment]
Agreed and done :)

1. Removed ATZVersion.h
2. `VERSION` in the Makefile is now populated from `Alcatraz-Info.plist`
3. Updated `-addVersionToWindow` to read from the bundle's infoDictionary.

Also, I took the liberty to improve the sed regex in the Makefile's `update_install_url` to better handle semver.

-------------------

Somewhat unrelated, but I'm not sure what the

    rm -rf ${BUNDLE_NAME}

and

    cp -r ${INSTALL_PATH} ${BUNDLE_NAME}

lines in the Makefile's `build` rule are supposed to do. Could you clarify that for me, please? Are those just for backup purpose?

**Comment by supermarin** [comment]
> Somewhat unrelated, but I'm not sure what the
rm -rf ${BUNDLE_NAME}
and
cp -r ${INSTALL_PATH} ${BUNDLE_NAME}
lines in the Makefile's build rule are supposed to do. Could you clarify that for me, please? Are those just for backup purpose?

This is mostly a workaround for not specifying a ton of `xcodebuild` flags and telling it to build locally.
Basically, when you build a plugin, the binary goes to `~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin`, which is `$INSTALL_PATH`.

We need to take that binary, compress it and upload to Github releases.
So these lines are a hack for having `Alcatraz.xcplugin` locally in your folder each time you build.

The right approach to this would be to specify something like `xcodebuild ... CONFIGURATION_BUILD_DIR=$PWD) build`.
Given we're planning to stop building locally, I don't think we should be spending time in improving this build system :)

**Comment by supermarin** [comment]
Thanks for the contribution @guillaume-algis!

**Pull request merged**
