### PR TITLE
Clear cached downloads in order to support nibs

### PR DESCRIPTION
**Pull request by orta**
Makes the changes requested in #233 - thanks @johnno1962

### CODE REVIEW

**Comment by jurre** [comment]
Thanks @orta and @johnno1962, I totally missed that we didn't merge that one

**Comment by johnno1962** [comment]
http://community.spartangames.co.uk/uploads/gallery/album_853/gallery_3406_853_429.jpeg thanks!

**Comment by supermarin** [comment]
Thanks @johnno1962 @orta!
I'll ship an update soon

**Comment by johnno1962** [comment]
Just updated alcatraz and encountered this again. Is this live?

**Comment by orta** [comment]
no

**Comment by supermarin** [comment]
let's make it live

**Comment by supermarin** [comment]
@orta @johnno1962 it's live!

**Comment by orta** [comment]
Giphy

**Comment by johnno1962** [comment]
Thanks for this.. hate to be a buzz kill however the problem is still there.
I’ve just tried the following:

updated Alcatraz using script.. can’t install Xprobe
built from your github zip.. no luck - stil get nib problem
Applied change I originally suggested.. works

No idea why

**Comment by supermarin** [comment]
uhhh..damnit :/

@orta have you tested the fix from the commit?

**Comment by orta** [comment]
Nope, just moved the command to where you wanted it. We should put the original version back in.

**Comment by supermarin** [comment]
K i'll take a look, @johnno1962 would you mind sending me the repro steps / plugin name?
thanks!

**Comment by johnno1962** [comment]
Xprobe is the one I’ve had the most issues with but also GitDiff. I can’t promise you’lll be able to replicate it as the problem only crops up on the second build when Xcode thinks it has already processed nibs. Hence the rash of problems now that people are upgrading to 6.2 who already had the plugin installed.

**Comment by johnno1962** [comment]
Let me know when you have a release ready and I can  test it for you.

**Comment by johnno1962** [comment]
This seems to be fixed now. Thanks! BTW noticed Alcatraz seems to be blocked somehow in Xcode 6.4 Beta. Time for: https://github.com/supermarin/Alcatraz/issues/196 ?

**Pull request merged**
