### PR TITLE
Support for script based installations

### PR DESCRIPTION
**Pull request by feinstruktur**
What this does is search for a script called `alcatraz.sh` in your project to build (or install!) a plugin. This should help support cases where a build of a project alone is not enough.

However, this mechanism can also be used to trigger a binary install by downloading a release and placing it in the plugins folder similar to what Alcatraz uses to bootstrap:

```
curl -fsSL https://raw.githubusercontent.com/supermarin/Alcatraz/master/Scripts/install.sh | sh
```

Placing this inside `alcatraz.sh` allows plugin authors to provide binaries for installation rather than building the plugin on the target system.

However, this comes with a big downside – you'd need to be able to trust plugin authors not to place something malicious inside `alcatraz.sh`. Now that I've written this I've convinced myself that this is a bad idea.

It's probably best if there's a mechanism to fetch a zip from a URL and unpack it into the plugins folder rather than drive this through a script.

I'll open this PR anyway, if only to have a discussion what I could do to get CoPilot (which this is for) working with Alcatraz.

### CODE REVIEW

**Comment by jurre** [comment]
What about just providing a `build.sh` and using that as a build step in xcode? We should support that already. That however does expose the same issues you've outlined :/

**Comment by feinstruktur** [comment]
You're right, this vulnerability already exists. Someone can put up a plugin right now and sneak in a script build step doing all sorts of things. Only exclusive binary distribution would prevent that I guess (again unless someone wants to do something malicious from within the plugin...)

For me it's much easier (and actually ready) if I use the build script straight away rather than adding another project file which then runs a script. Having to rename my existing project file away from `CoPilot.xcodeproj` is actually quite messy. I did rename it from `CoPilotPlugin.xcodeproj` to `CoPilot.xcodeproj` very recently in order to support Alcatraz and it wasn't trivial (see https://github.com/feinstruktur/CoPilot/pull/24). I'd love to avoid having to do that again ;)

**Comment by feinstruktur** [comment]
So I guess the question is, would you support this script based installation given that the vulnerability currently exists and trust is essential already?

**Comment by feinstruktur** [comment]
Just wanted to check if there's anything I can change to make this 'merge-able'. Happy to weak it if it's something you'd consider to add.

**Comment by jurre** [comment]
@supermarin could you have a look at this?

**Comment by supermarin** [comment]
@jurre sorry I was on vacation and offline.
I'll try to catch up with PRs this week

**Comment by jurre** [comment]
:+1: :+1: :sun_with_face:

**Comment by feinstruktur** [comment]
Gents, is there anything I can do to help getting this one across the line? I'll be away for two weeks from Sunday and I wouldn't want it to grow stale during that time ;) Cheers, Sven

**Comment by supermarin** [comment]
@feinstruktur Thank you for this contribution, very much appreciated.

Honestly, I think we should not support this kind of stuff, 'cause we're switching to binary distributions.
This means, developers will build plugins on their own machines, and upload to Github releases.

We're all just out of time and energy to pull the trigger and do it, but it'll happen pretty soon.
This way, we'll solve 2 problems:
- CocoaPods, Carthage, any kind of deps
- Closed source plugins

The other downside, like mentioned, is the __super obvious__ vulnerability and a potential for people to do various kinds of things in `alcatraz.sh`.

Other than that, the PR is conceptually really good and I hope this will not discourage you from further contributions.

**Comment by feinstruktur** [comment]
Makes sense, Marin. Is there a branch tracking binary releases? Or a rough ETA?

**Comment by supermarin** [comment]
I'll get back to you on this issue or via email.
Starting very soon.

**Pull request closed without merging**
