### PR TITLE
Support Xcode 6.3.2 + 6.4

### LINKED ISSUE #273: Alcatraz doesn't work with Xcode 6.3.2
Have you guys looked into getting Alcatraz to work the GM Build of Xcode 6.3.2 or update the install script to work with the version. I ran it many times and nothing seems to be working.

### PR DESCRIPTION
**Pull request by jurre**
This combines #270 and #271 and fixes some style nitpicks.

Thanks @neonichu and @Pyroh.

@supermarin could you merge + release this? Otherwise I can do it later today. Fixes #273 #263 #269.

### CODE REVIEW

**Comment by ajimix** [comment]
Would be nice to have this asap as today everyone is updating and nothing is working :(

**Comment by crisredfi** [comment]
yes please, update asap..

**Comment by neonichu** [comment]
@jurre great work :beers:

**Comment by supermarin** [comment]
Thanks everyone! :beers:

**Comment by supermarin** [comment]
@jurre if you don't mind, please do a release. otherwise I can do it later today, it's 4 AM here

**Comment by jurre** [comment]
<3 i'll do it later today, gngn

**Pull request merged**
