### PR TITLE
Add UDID for Xcode 6.3

### PR DESCRIPTION
**Pull request by davelyon**
Xcode 6.3 (release) support

Not sure if this is all that is needed. Let me know if there is more that needs to be done and I'll be happy to help!

### CODE REVIEW

**Comment by davelyon** [comment]
Got too excited that the item showed up again, getting a crash now:

```
Process:               Xcode [87043]
Path:                  /Applications/Xcode.app/Contents/MacOS/Xcode
Identifier:            com.apple.dt.Xcode
Version:               6.3 (7569)
Build Info:            IDEFrameworks-7569000000000000~2
App Item ID:           497799835
App External ID:       812135760
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Xcode [87043]
User ID:               501

Date/Time:             2015-04-08 15:45:28.050 -0700
OS Version:            Mac OS X 10.10.2 (14C109)
Report Version:        11

Time Awake Since Boot: 250000 seconds
Time Since Wake:       6100 seconds

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Application Specific Information:
ProductBuildVersion: 6D570
UNCAUGHT EXCEPTION (NSInternalInconsistencyException): -[NSNib initWithNibNamed:bundle:] could not load the nibName: ATZPackageListTableCellView in bundle NSBundle </Users/dlyon/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin> (loaded).

**Comment by kattrali** [comment]
Thanks, will check it out. :)

**Comment by kattrali** [comment]
Can you try cleaning and rebuilding?

**Comment by davelyon** [comment]
A clean build seems to have fixed it! Thanks @kattrali

**Pull request merged**
